float x; // variables//rrrrrwwwddddddddddwwwdswaaaas
float y;
float ball;
float ballin;
float BALL;
float BALLIN;
int score = 0;
float speed0;
float speed1;
float y1;
float x1;
float [] hitbox;
float luck = -1;
float y2;
float x2;
float s = 0;
int p = 1;
int qwertz = -1000000000;
float speed = 10;
int hiscore = 69;
float [] t;
PImage troll;
float d = 0;
float l = 255;
int h = 0;
float w = 6;
float [] nav;
float [] nax;
int N = 3;
boolean pause = false;
