name: Create website

on:
  push:
    paths:
      - .github/workflows/create_website.yaml
      - 'docs/**'
  pull_request:
    paths:
      - .github/workflows/create_website.yaml
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Render HTML
        run: mkdocs gh-deploy --force
